"""
ganesh/tools/export_latex.py
=============================
Exports a completed GaneshDocument (final_output markdown) to a
typeset PDF via LaTeX. Read-only against the write/synthesize
pipeline -- runs after G5 has populated final_output.
"""
import re
import subprocess
from pathlib import Path
from datetime import datetime

OUTPUT_DIR = Path("/mnt/d/brahm/data/outputs")


def _escape_latex(text: str) -> str:
    """Escape LaTeX special characters in plain text segments."""
    replacements = [
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"),
        ("%", r"\%"),
        ("$", r"\$"),
        ("#", r"\#"),
        ("_", r"\_"),
        ("{", r"\{"),
        ("}", r"\}"),
        ("~", r"\textasciitilde{}"),
        ("^", r"\textasciicircum{}"),
    ]
    for old, new in replacements:
        text = text.replace(old, new)
    return text


def _subscript_chemical_formulas(text: str) -> str:
    """Convert patterns like MoS2, SiO2, MoO3 into MoS\\textsubscript{2} etc."""
    return re.sub(
        r"([A-Z][a-zA-Z]*?)(\d+)",
        lambda m: f"{m.group(1)}\\textsubscript{{{m.group(2)}}}",
        text,
    )


def _markdown_to_latex_body(markdown_text: str) -> str:
    """
    Minimal markdown -> LaTeX converter for GANESH's output format.
    Handles: # / ## / ### headers, plain paragraphs.
    """
    lines = markdown_text.split("\n")
    out = []
    for line in lines:
        stripped = line.strip()
        if not stripped:
            out.append("")
            continue
        if stripped.startswith("### "):
            content = _subscript_chemical_formulas(_escape_latex(stripped[4:]))
            out.append(f"\\subsection*{{{content}}}")
        elif stripped.startswith("## "):
            content = _subscript_chemical_formulas(_escape_latex(stripped[3:]))
            out.append(f"\\section*{{{content}}}")
        elif stripped.startswith("# "):
            continue
        elif stripped.startswith("_") and stripped.endswith("_"):
            content = _subscript_chemical_formulas(_escape_latex(stripped.strip("_")))
            out.append(f"\\textit{{{content}}}")
        else:
            content = _subscript_chemical_formulas(_escape_latex(stripped))
            out.append(content + "\n")
    return "\n".join(out)


LATEX_TEMPLATE = r"""\documentclass[11pt]{article}
\usepackage[margin=1in]{geometry}
\usepackage{times}
\usepackage[utf8]{inputenc}
\usepackage{titling}
\setlength{\droptitle}{-2em}

\title{%(title)s}
\author{Generated by GANESH (BRAHM)}
\date{%(date)s}

\begin{document}
\maketitle

%(body)s

\end{document}
"""


def export_latex(repo, document_id: int, config: dict) -> dict:
    row = repo.fetch_one(
        "SELECT title, document_type, final_output FROM GaneshDocument WHERE id = ?",
        (document_id,),
    )
    if not row:
        raise ValueError(f"GaneshDocument {document_id} not found")
    if not row["final_output"]:
        raise ValueError(
            f"GaneshDocument {document_id} has no final_output -- "
            f"run /documents/synthesize (G5) first."
        )

    title = _subscript_chemical_formulas(_escape_latex(row["title"] or "Untitled Document"))
    body = _markdown_to_latex_body(row["final_output"])

    tex_source = LATEX_TEMPLATE % {
        "title": title,
        "date": datetime.utcnow().strftime("%Y-%m-%d"),
        "body": body,
    }

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    tex_path = OUTPUT_DIR / f"ganesh_document_{document_id}.tex"
    pdf_path = OUTPUT_DIR / f"ganesh_document_{document_id}.pdf"

    tex_path.write_text(tex_source, encoding="utf-8")

    result = None
    for _ in range(2):
        result = subprocess.run(
            ["pdflatex", "-interaction=nonstopmode", "-output-directory", str(OUTPUT_DIR), str(tex_path)],
            capture_output=True,
            text=True,
            timeout=60,
        )

    if not pdf_path.exists():
        raise RuntimeError(
            f"pdflatex failed to produce output. Last run stdout tail:\n"
            f"{result.stdout[-2000:]}"
        )

    return {
        "status":   "success",
        "document_id": document_id,
        "tex_path": str(tex_path),
        "pdf_path": str(pdf_path),
    }
